-- Creazione tabella centralizzata per la gestione degli invii automatici
-- e popolamento iniziale con i job schedulati riconosciuti nel progetto.

IF OBJECT_ID('Traceability_RS.dbo.AutomaticEmailJobs', 'U') IS NULL
CREATE TABLE Traceability_RS.dbo.AutomaticEmailJobs (
    JobName              VARCHAR(100)  NOT NULL PRIMARY KEY,
    DisplayName          NVARCHAR(255) NOT NULL,
    FunctionName         VARCHAR(200)  NULL,
    ModulePath           VARCHAR(255)  NULL,
    Description          NVARCHAR(MAX) NULL,
    Timing               NVARCHAR(500) NULL,
    RecipientsSettingKey VARCHAR(100)  NULL,
    IsEnabled            BIT           NOT NULL DEFAULT 1,
    LastRunAt            DATETIME      NULL,
    LastRunStatus        VARCHAR(50)   NULL,
    LastRunMessage       NVARCHAR(500) NULL,
    NextRunAt            DATETIME      NULL,
    LockUntil            DATETIME      NULL,
    CreatedAt            DATETIME      NOT NULL DEFAULT GETDATE(),
    UpdatedAt            DATETIME      NOT NULL DEFAULT GETDATE()
);
GO

-- Popolamento iniziale: i job gia' esistenti nell'applicazione.
-- I valori possono essere modificati dalla form "Gestione Invii Automatici".

MERGE INTO Traceability_RS.dbo.AutomaticEmailJobs AS target
USING (VALUES
    ('purchasing_reminder',
        N'Reminder acquisti materiali indiretti',
        'check_and_send_purchasing_reminder',
        'indirect_materials_stock_data.py',
        N'Invia reminder agli acquisti per le richieste di riordino non confermate.',
        N'Lun-Sab 10:00',
        'sys_email_acquista_indiretti'),
    ('indirect_reorder',
        N'Riordino materiali indiretti sotto scorta',
        'check_and_send_reorder',
        'indirect_materials_stock_data.py',
        N'Invia un''unica email giornaliera con i materiali indiretti sotto la scorta minima.',
        N'Lun-Sab 07:30',
        'Sys_email_reorder_indirect_materials'),
    ('fqc_shift_1530_2330',
        N'Report FQC fine turno',
        'run_fqc_shift_1530 / run_fqc_shift_2330',
        'fqc_email.py',
        N'Invia riepilogo verifiche FQC fine turno alle 15:30 e 23:30.',
        N'Lun-Sab 15:30 e 23:30',
        'Sys_check_final_product'),
    ('fails_daily_email',
        N'Report giornaliero FAIL boards',
        'run_fails_daily_email',
        'fails_daily_email.py',
        N'Report Excel e PDF sui FAIL boards del giorno/mese/anno.',
        N'Tutti i giorni lavorativi 07:00',
        'Sys_Fail_report'),
    ('missing_alloy_check',
        N'Avviso codici PTHM senza dato alloy',
        'run_missing_alloy_check',
        'material_consumption_report.py',
        N'Avviso sui codici PTHM senza dato alloy.',
        N'Lun-Sab 08:05',
        'Sys_missing_data_alloy'),
    ('plan_alert_escalation',
        N'Escalation alert piano produzione',
        'check_and_escalate',
        'plan_alert_escalation.py',
        N'Escalation per alert piano produzione non giustificati entro i tempi previsti.',
        N'Ogni ~60 min 07:00-18:00 e 22:00-23:59',
        'Sys_email_control_plan'),
    ('plan_responsibles_daily',
        N'Email giornaliera responsabili piano',
        'send_daily_responsibles_email',
        'plan_responsibles.py',
        N'Email ai responsabili con discrepanze e urgenze del piano.',
        N'Giorni lavorativi RO 08:00',
        'Sys_email_responsabili_piano'),
    ('stale_clients_report',
        N'Report client con versione obsoleta',
        'send_stale_clients_email',
        'stale_clients_report.py',
        N'Email con l''elenco dei PC che non hanno aggiornato l''applicazione.',
        N'Giorni lavorativi 08:00',
        'Sys_stale_clients_email'),
    ('fai_enforcement',
        N'FAI enforcement / escalation',
        'run_shift_check / process_pending_escalations / run_planning_based_enforcement',
        'fai_enforcement.py',
        N'Invio referat PDF e email per FAI enforcement/escalation.',
        N'Ogni 60 sec (continuo)',
        'Sys_email_fai_enforcement'),
    ('fai_autocheck',
        N'Notifiche preventive FAI da PlanningMachine',
        'run_autocheck_cycle',
        'fai_autocheck.py',
        N'Notifiche preventive FAI generate dalla pianificazione macchine.',
        N'Ogni 30 min',
        'Sys_email_fai_autocheck'),
    ('weekly_npi_overview',
        N'NPI Overview settimanale',
        '_send_weekly_npi_overview',
        'main.py',
        N'Report Excel + grafico con overview settimanale progetti NPI.',
        N'Lunedi 09:00',
        'Sys_email_general_napi'),
    ('weekly_overtime_unauthorized',
        N'Report straordinari non autorizzati',
        'send_weekly_unauthorized_overtime_email',
        'overtime/overtime_manager.py',
        N'Report settimanale degli straordinari non ancora autorizzati.',
        N'Lunedi 09:00',
        'Sys_email_overtimeNotAuth'),
    ('monthly_overtime_report',
        N'Report mensile straordinari approvati',
        'generate_and_send_monthly_overtime_report',
        'overtime/overtime_manager.py',
        N'Report mensile degli straordinari approvati.',
        N'Primo giorno lavorativo del mese 09:00',
        'Sys_email_overtimeMonthlyReport'),
    ('monthly_report_generic',
        N'Report mensile generic verification',
        '_monthly_report_worker',
        'main.py',
        N'Report Excel mensile generic verification.',
        N'Primo giorno lavorativo del mese 09:00',
        'Sys_Verify_check_fail'),
    ('kanban_refill_check',
        N'Richiesta refill KanBan',
        '_kanban_refill_check_worker',
        'main.py',
        N'Email di richiesta refill KanBan con allegato Excel.',
        N'Ogni 8 ore',
        'Sys_email_KanBanRefill'),
    ('weekly_visitor_email',
        N'Lista visitatori programmata settimana',
        '_check_weekly_visitor_email',
        'main.py',
        N'Email settimanale con la lista dei visitatori programmata da lunedi a domenica.',
        N'Lunedi (orario variabile)',
        'Sys_email_management'),
    ('label_scrap_shift_end',
        N'Scarti etichette fine turno',
        '_process_shift_end',
        'label_scrap_monitor.py',
        N'Email con PDF/Excel degli scarti etichette 15 min prima della fine turno.',
        N'07:15 / 15:15 / 23:15',
        'sys_email_labelScrap'),
    ('shift_handover_unconfirmed',
        N'Alert cambio turno non confermato',
        'ShiftHandoverMonitor',
        'shift_handover_monitor.py',
        N'Alert se un cambio turno non viene confermato entro 60 min.',
        N'Continuo (postazione specifica)',
        'sys_email_Allert_Shift'),
    ('npi_auto_notifications',
        N'Notifiche consolidate task NPI',
        '_check_and_send_notifications',
        'npi/npi_auto_notifications.py',
        N'Notifiche consolidate per task NPI in scadenza/scaduti.',
        N'Ogni giorno lavorativo ~08:00',
        NULL),
    ('npi_commerciali_weekly',
        N'Riepilogo settimanale progetti NPI per commerciali',
        'run',
        'npi_commerciali_weekly_email.py',
        N'Riepilogo settimanale dei progetti NPI destinato ai commerciali.',
        N'Venerdi 17:00',
        'Sys_email_npi_global_view'),
    ('touchup_no_response',
        N'Escalation Touch-Up senza risposta',
        'escalate_unanswered_reports',
        'touchup_logic.py',
        N'Escalation per segnalazioni Touch-Up senza risposta.',
        N'Ogni 5 min',
        'Sys_email_TouchUp_warning'),
    ('kit_dashboard_alert',
        N'Alert web server Kit Dashboard down',
        'send_alert',
        'kit_dashboard/server_watcher.py',
        N'Email se il web server della Kit Dashboard non risponde.',
        N'Continuo',
        'Sys_email_Kit_materiali'),
    ('scrap_validation_reminder',
        N'Sollecito validazione scorie/rientri pendenti',
        'main',
        'scrap_validation_reminder.py',
        N'Sollecito per scorie/rientri pendenti da validare.',
        N'Ogni ~30 min (Task Scheduler)',
        'Sys_email_valida_restituzioni'),
    ('kit_requests_reminder',
        N'Reminder richieste materiale kit PENDING',
        'main',
        'kit_requests_reminder.py',
        N'Reminder per richieste materiale kit ancora in stato PENDING.',
        N'Ogni 5 min (Task Scheduler)',
        'Sys_email_Kit_materiali')
) AS source (JobName, DisplayName, FunctionName, ModulePath, Description, Timing, RecipientsSettingKey)
ON target.JobName = source.JobName
WHEN NOT MATCHED THEN
    INSERT (JobName, DisplayName, FunctionName, ModulePath, Description, Timing, RecipientsSettingKey, IsEnabled)
    VALUES (source.JobName, source.DisplayName, source.FunctionName, source.ModulePath, source.Description, source.Timing, source.RecipientsSettingKey, 1);
GO
